(1.7.6) Fix issues with non- pthreads builds for subrcModel*
git-svn-id: file:///home/git/hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/preprocessCore@63795 bc3139a8-67e5-0310-9ffc-ced21a209358

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -15,6 +15,22 @@ dnl
 dnl Are things (still) the same ?
 dnl (taken from the 'writing R extensions manual')
 
+dnl Now find the compiler and compiler flags to use
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+       echo "could not determine R_HOME"
+       exit 1
+fi
+CC=`"${R_HOME}/bin/R" CMD config CC`
+CPP=`"${R_HOME}/bin/R" CMD config CPP`
+CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
+CPPFLAGS=`"${R_HOME}/bin/R" CMD config CPPFLAGS`
+AC_PROG_CC
+AC_PROG_CPP
+
+
+
+
 
 # Checks for libraries.
 use_pthreads=no
